spec:
   name: waqasshami-hugo
   static_sites:
   - build_command: rm -r ./public; hugo --minify --destination ./public
     environment_slug: hugo
     git:
       branch: main
       repo_clone_url: https://github.com/waqas-shami/waqasshami-hugo.git
     name: waqasshami-hugo